library(dplyr)
trip <- read.csv(file='data/trip.csv')
weather <- read.csv(file = 'data/weather.csv')
station <- read.csv(file = 'data/station.csv')
forMap <- select(trip, "from_station_name",'to_station_name', 'from_station_id', 'to_station_id')
station <- select(station, "station_id", "lat", "long")
colnames(station) <- c("from_station_id", "from_lat", "from_long")
forMap <- merge(forMap,station)
colnames(station) <- c("to_station_id", "to_lat", "to_long")
forMap <- merge(forMap,station)
View(forMap)
write.csv(forMap,file = 'data/forMap.csv')
